# Generated by Django 3.2.5 on 2021-09-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
